### ISSUE TITLE
迁移到 VitePress

### ISSUE THREAD

**Issue by LittleSound** [project-trans/vitepress-theme-project-trans#4]
迁移中的 RLE 部署在： [next.rle.wiki](https://next.rle.wiki/)
工作分支：https://github.com/project-trans/RLE-wiki/tree/next
里程碑（Milestone）: https://github.com/project-trans/RLE-wiki/milestone/1

欢迎 PR！想要帮忙可以 fork 后根据这个 next 分支创建子分支然后创建合并到 next 分支的 PR。为了避免与其他人重复，请在开始处理问题之前创建一个 Issue。

## 主要关注点
- [x] GitHub Action 项目部署
  - https://github.com/project-trans/RLE-wiki/commit/7937803573a2deb939cde2f4742a159efdd96d4f
- [x] 自动生成 themeConfig sidebar 
  - https://github.com/project-trans/RLE-wiki/pull/223
  - https://github.com/project-trans/RLE-wiki/issues/222
- [x] 自动生成位于页面顶部的文章标题和文章信息
  - project-trans/RLE-wiki#225
  - project-trans/RLE-wiki#224
- [x] https://github.com/vinta/pangu.js/
  - https://github.com/project-trans/RLE-wiki/commit/0ebf909e2226888c1750f45ced88bacac385a8a5#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R14
- [x] 侧边栏排列顺序
  - project-trans/RLE-wiki#226
  - project-trans/RLE-wiki#232 
  - - [x] https://github.com/project-trans/vitepress-theme-project-trans/issues/2
- [x] project-trans/RLE-wiki#322
- [x] 移除除了 Noto CJK 以外字體的 U+2713（↩️）
  - https://github.com/project-trans/SOC-8/pull/3
    - [x] backported: ?
- [x] 文章底部根据 git log 显示变更日志（最新一条变更日志直接显示，其余折叠）
  - project-trans/RLE-wiki#233
  - project-trans/RLE-wiki#234
- [x] 搜索功能
  - project-trans/RLE-wiki#236
- [x] https://github.com/project-trans/SOC-8/issues/9
  - https://github.com/project-trans/SOC-8/pull/10
    - [x] backported: https://github.com/project-trans/RLE-wiki/commit/6b54f59b4f7dd9058e2403c96b75913e2590428e
  - https://github.com/project-trans/SOC-8/pull/11/
    - [x] backported: https://github.com/project-trans/RLE-wiki/commit/071c65e935fdf8bd8773261b72e4d93a08f32fe8
- [x] https://github.com/project-trans/RLE-wiki/issues/275
- [x] https://github.com/project-trans/RLE-wiki/issues/274
  - https://github.com/project-trans/RLE-wiki/pull/297
- [x] https://github.com/project-trans/RLE-wiki/issues/273
- [x] https://github.com/project-trans/RLE-wiki/issues/342
 
## 需要修复的问题
- [x] project-trans/RLE-wiki#228
- [x] https://github.com/project-trans/vitepress-theme-project-trans/issues/3
- [x] https://github.com/project-trans/RLE-wiki/issues/280
- [x] https://github.com/project-trans/RLE-wiki/issues/412

## Project-trans 其它仓库中的相关讨论
- [x] https://github.com/project-trans/MtF-wiki/issues/852
- [x] https://github.com/project-trans/MtF-wiki/issues/785

*待补充更多...*

**Comment by Cryolitia** [comment]
Project Trans Develop Team 工作年报

Vitepress 主题开发及迁移工作已圆满完成🎉

影响站点：
- https://RLE.wiki
- https://project-trans.org/SOC-8/
- https://transky.mtf.wiki/

感谢此阶段的所有贡献者！

任务周期：2023.9.6 — 2024.9.26
